Numpy is a fundamental library and provides support for large arrays and matrices along with collection of mathematical functins to operate on these data structures. 

In [2]:
import numpy as np
## create arrays using numpy
# create a 1D array
a = np.array([1, 2, 3, 4, 5])
print("1D array:", a)

1D array: [1 2 3 4 5]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
#shape of array
print("Shape of array:", a.shape)

Shape of array: (5,)


In [ ]:
#reshape to 2D array
b = a.reshape(1, 5)    ## 1 row and 5 columns and still 5 elements. with 2 square brackets
print("2D array:\n", b)

2D array:
 [[1 2 3 4 5]]


In [ ]:
# shape of 2D array
c = np.array([[1, 2, 3, 4, 5, 6]])
c.shape

(1, 6)

In [ ]:
d = np.array([[1, 2, 3], [4, 5, 6]])  # 2 rows and 3 columns and it is 2D array
print(d)
d.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
np.arange(0, 10, 2).reshape(1, 5)  ## start, stop, step and 1 row and 5 columns

array([[0, 2, 4, 6, 8]])

In [19]:
np.arange(1,10)  # create an array of integers from 1 to 9

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.ones((2, 3))  ## create a 2x3 array filled with ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#identity matrix
np.eye(4)  ## create a 4x4 identity matrix. only diagonal elements are 1 and rest are 0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# Attributes of numpy array

array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", array)
print("Shape:", array.shape)  # shape of the array
print("Type of array:", type(array))  # type of the array
print("Data type:", array.dtype)  # data type of the elements in the array
print("Number of dimensions:", array.ndim)  # number of dimensions of the array
print("Size:", array.size)  # total number of elements in the array
print("Item size (bytes):", array.itemsize)  # size of each element in bytes

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Type of array: <class 'numpy.ndarray'>
Data type: int64
Number of dimensions: 2
Size: 6
Item size (bytes): 8


In [ ]:
# Numpy vectorized operations. It does element-wise operation
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

#Element-wise addition
print("Addition:", a + b)
#Element-wise subtraction
print("Subtraction:", a - b)
#Element-wise multiplication
print("Multiplication:", a * b)
#Element-wise division
print("Division:", a / b)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [21]:
# Universal functions (ufuncs) in numpy. It is a function that operates element-wise on arrays.. It affects all the elements in the array
a = np.array([1, 2, 3, 4, 5])
print(np.sqrt(a))  # square root of each element
print(np.exp(a))  # exponential of each element
print(np.log(a))  # natural logarithm of each element
print(np.sin(a))  # sine of each element

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
# array slicing and indexing
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])   # 3 rows and 3 columns
print("Original array:\n", a)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# how to access single element. Indexing start with 0
print("Element at [0,0]:", a[0,0])  # first row and first column
print("Element at [1,2]:", a[1,2])  # second row and third column


Element at [0,0]: 1
Element at [1,2]: 7


In [ ]:
a[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [36]:
a[0:1, 0:4]

array([[1, 2, 3, 4]])

In [39]:
a[1: , 1:3]

array([[ 6,  7],
       [10, 11]])

In [40]:
#Modify array element
a[0,0] = 100
print("Modified array:\n", a)

Modified array:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [41]:
a[1:] = 100
print("Modified array:\n", a)

Modified array:
 [[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [45]:
# Logical operations
data = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
data > 5   # check if each element is greater than 5 true or false

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [46]:
# To retrive the elements that are greater than 5
data[data >= 5]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
data[(data >=5) & (data <= 8)]  # retrive the elements that are greater than or equal to 5 and less than or equal to 8

array([5, 6, 7, 8])